name: What_checkout_does
on: pull_request

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check files
      uses: actions/checkout@v4
    - name: Print files
      run: |
        ls -ltr
        java -version
    - name: Create directory
      uses: actions/checkout@v4
      with:
        repository: apache/tomcat
        ref: master
        path: ./new_dir
